version: "3"

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbit
    environment:
      PYTHONPATH: "/code/src"
  worker:
    build: .
    command: celery -A celery_channels_test worker -P gevent -c 5
    working_dir: /code/src
    volumes:
      - .:/code
    links:
      - rabbit
    depends_on:
      - rabbit
  # RabbitMQ for celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672" # we forward this port because it's useful for debugging
      - "15672:15672" # here, we can access rabbitmq management plugin
  # Redis for channels
  cache:
    image: redis:6.2-alpine
